# Generated by Django 4.1.3 on 2022-11-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
