# Generated by Django 4.1.3 on 2022-11-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment_cate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cate',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clean', models.FloatField()),
                ('hit', models.FloatField()),
                ('noise', models.FloatField()),
                ('optionrate', models.FloatField()),
                ('secu', models.FloatField()),
                ('day_light', models.FloatField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.home')),
            ],
        ),
    ]
