# Generated by Django 4.1.3 on 2022-11-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_rating_clean_alter_rating_day_light_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='home',
            new_name='homes',
        ),
    ]
