# Generated by Django 4.1.3 on 2022-11-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_home_rating_homes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='clean',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='day_light',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='hit',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='noise',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='optionrate',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='secu',
        ),
        migrations.AddField(
            model_name='comment',
            name='clean',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='comment',
            name='day_light',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='comment',
            name='hit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='comment',
            name='noise',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='comment',
            name='optionrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='comment',
            name='secu',
            field=models.FloatField(default=0.0),
        ),
    ]
