# Generated by Django 4.1.3 on 2022-11-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_rating_clean_remove_rating_day_light_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ave',
            field=models.FloatField(null=True),
        ),
    ]
