# Generated by Django 4.1.3 on 2022-11-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_comment_ave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ave',
            field=models.FloatField(default=0.0),
        ),
    ]
