# Generated by Django 4.1.3 on 2022-11-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_comment_ave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ave',
        ),
        migrations.AddField(
            model_name='rating',
            name='ave',
            field=models.FloatField(default=0.0),
        ),
    ]
