# Generated by Django 4.1.3 on 2022-11-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_comment_ave_rating_ave'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='deposit',
            field=models.FloatField(default=0.0),
        ),
    ]
